In [1]:
import numpy as np

### Exercise 1: Creating Arrays and Using Attributes

Create a 1D array of numbers from 1 to 10 using np.arange().

Create a 2D array of shape (3, 4) filled with ones using np.ones().

Use the shape and dtype attributes to display the shape and data type of both arrays.

In [92]:
import numpy as np 

np_arange = np.arange(1, 11)
print(np_arange)
print("Shape of np_arange:", np_arange.shape)
print("Data type of np_arange:", np_arange.dtype)
print()
np_ones = np.ones((3, 4))
print(np_ones)
print("Shape of np_ones:", np_ones.shape)
print("Data type of np_ones:", np_ones.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
Shape of np_arange: (10,)
Data type of np_arange: int64

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape of np_ones: (3, 4)
Data type of np_ones: float64


### Exercise 2: Generating Random Values and Reshaping Arrays

Create an array of 10 random integers between 0 and 50 using np.random.randint().

Reshape the array into a 2D array with shape (2, 5).

Find the minimum and maximum values in the array using the min() and max() methods.

In [14]:
# The first code snippet seperates generating the array and reshaping it into two seperate steps. The second code snippet is more concise.
# Both snippets generate the expected output

In [12]:
import numpy as np

random_array = np.random.randint(0, 50, 10)
print(random_array)

reshaped_array = random_array.reshape(2, 5)
print(reshaped_array)

print("The min value in the array is", reshaped_array.min())
print("The max value in the array is", reshaped_array.max())


[45 42 43 20 21 39 30 11 46  8]
[[45 42 43 20 21]
 [39 30 11 46  8]]
The min value in the array is 8
The max value in the array is 46


In [13]:
import numpy as np

random_array = np.random.randint(0, 50, 10).reshape(2, 5)
print(random_array)

print("The min value in the array is", random_array.min())
print("The max value in the array is", random_array.max())

[[34 40 19 45  5]
 [32  6 11 38 24]]
The min value in the array is 5
The max value in the array is 45


### Exercise 3: Indexing and Boolean Indexing

Create a 2D array from the following list of lists:

[[12, 15, 22],
 [33, 45, 52],
 [17, 28, 39]]

Extract the first row of the array.

Extract the element in the second row, third column.

Use a boolean index to extract all values greater than 30.

In [9]:
import numpy as np

data = [[12, 15, 22], [33, 45, 52], [17, 28, 39]]
array_2d = np.array(data)
print(array_2d)

first_row = array_2d[0]
print(first_row)

element = array_2d[1, 2]
print(element)

gt_30 = array_2d > 30
print("Values greater than 30:", array_2d[gt_30])


[[12 15 22]
 [33 45 52]
 [17 28 39]]
[12 15 22]
52
Values greater than 30: [33 45 52 39]


### Exercise 4: Broadcasting and Mathematical Operations

Create a 1D array with 5 random values between 0 and 10 using np.random.rand().

Create another 1D array of 5 ones.

Perform the following operations:

Addition: Add the two arrays.

Multiplication: Multiply the two arrays element-wise.

Use broadcasting to add 5 to each element of the first array.

In [3]:
import numpy as np

random_array2 = np.random.randint(0, 10, 5)
print(random_array2)

ones_array = np.ones(5)
print(ones_array)

print("Adding the arrays:", random_array2 + ones_array)

print("Muliplying the arrays:", random_array2 * ones_array)

random_array2[0:5] += 5
print("Broadcasting:", random_array2)


[9 3 3 6 9]
[1. 1. 1. 1. 1.]
Adding the arrays: [10.  4.  4.  7. 10.]
Muliplying the arrays: [9. 3. 3. 6. 9.]
Broadcasting: [14  8  8 11 14]


### Exercise 5: Using NumPy Ufuncs

Create a 1D array of numbers from 1 to 16 using np.arange().

Use the sqrt() function to calculate the square root of each element in the array.

Use the sum() function to calculate the sum of all elements in the array.

Use the mean() function to calculate the mean of the array.

In [98]:
import numpy as np

np_arange = np.arange(1, 17)
print(np_arange)

print("sqrt() of the array elements:", np.sqrt(np_arange))

print("sum() of the array elements:", np.sum(np_arange))

print("mean() of the array elements:", np.mean(np_arange))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
sqrt() of the array elements: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.        ]
sum() of the array elements: 136
mean() of the array elements: 8.5


### Bonus Challenge (Optional):

Create a 2D array with shape (4, 4) using np.linspace() to generate values from 1 to 16.

Reshape it into a 4x4 matrix.

Calculate the sum of each row and each column using sum(axis=1) and sum(axis=0), respectively.

In [7]:
import numpy as np

array = np.linspace(1, 16, 16).reshape(4, 4)

print(array)

row_sums = array.sum(axis=1)
column_sums = array.sum(axis=0)

print("Sum of each row: ", row_sums)
print("Sum of each column: ", column_sums)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
Sum of each row:  [10. 26. 42. 58.]
Sum of each column:  [28. 32. 36. 40.]
