In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
np.array([1,3,2,4,6,7.8])

array([1. , 3. , 2. , 4. , 6. , 7.8])

In [6]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.random.randint(1,9,4)

array([5, 7, 7, 1])

In [11]:
np.array([[1,2,3,],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(12).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
rand_15 = np.random.randint(1,11,15).reshape(5,3)

In [20]:
rand_15

array([[9, 6, 9],
       [9, 5, 9],
       [6, 5, 7],
       [3, 4, 9],
       [6, 7, 6]])

In [21]:
rand_15.min()

np.int64(3)

In [23]:
rand_15.shape

(5, 3)

In [24]:
rand_15.dtype

dtype('int64')

In [25]:
rand_1d = np.random.randint(1,26,12)

In [26]:
rand_1d

array([12,  7, 23, 21,  9, 18, 12, 18, 12, 17, 16, 23])

In [27]:
rand_1d[0]

np.int64(12)

In [28]:
rand_1d[-1]

np.int64(23)

In [29]:
rand_1d[:6]

array([12,  7, 23, 21,  9, 18])

In [31]:
rand_1d[[1,3,5]]

array([ 7, 21, 18])

In [32]:
rand_15

array([[9, 6, 9],
       [9, 5, 9],
       [6, 5, 7],
       [3, 4, 9],
       [6, 7, 6]])

In [35]:
rand_15[1:4,0:2]

array([[9, 5],
       [6, 5],
       [3, 4]])

In [43]:
rand_15[np.ix_([0,2,4], [0,2])]

array([[9, 9],
       [6, 7],
       [6, 6]])

In [48]:
rand_subset = rand_15[np.ix_([2,4], [0, 2])]

In [49]:
rand_subset

array([[6, 7],
       [6, 6]])

In [50]:
rand_subset += 10

In [51]:
rand_subset

array([[16, 17],
       [16, 16]])

In [53]:
rand_subset = rand_15[1]

In [ ]:
rand_subset = rand_subset + 100

200

In [58]:
rand_subset

100

In [60]:
rand_15[1,2] = 25

In [61]:
rand_15 *= 2

In [62]:
rand_15

array([[18, 12, 18],
       [18, 10, 50],
       [12, 10, 14],
       [ 6,  8, 18],
       [12, 14, 12]])

In [63]:
r2 = np.array([1,2,3])
rand_15 + r2

array([[19, 14, 21],
       [19, 12, 53],
       [13, 12, 17],
       [ 7, 10, 21],
       [13, 16, 15]])

In [64]:
rand_cond = np.random.randint(1,21,25)

In [65]:
rand_cond

array([14, 14, 17, 12, 14,  5, 10, 17,  3, 11,  1, 18, 17, 20,  6,  9,  4,
        6, 20, 17, 13, 19,  7, 20,  1])

In [68]:
rand_cond > 10

array([ True,  True,  True,  True,  True, False, False,  True, False,
        True, False,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True, False,  True, False])

In [71]:
rand_cond[rand_cond > 10] *= 2

In [72]:
rand_cond

array([28, 28, 34, 24, 28,  5, 10, 34,  3, 22,  1, 36, 34, 40,  6,  9,  4,
        6, 40, 34, 26, 38,  7, 40,  1])

In [73]:
r1 = np.random.randint(1,11,10).reshape(5,2)
r2 = np.random.randint(100,1000,10).reshape(5,2)

In [74]:
r1 + r2

array([[511, 376],
       [892, 805],
       [483, 575],
       [266, 386],
       [237, 211]])

In [75]:
r3 = r1 + r2

In [76]:
np.sqrt(3)

np.float64(1.7320508075688772)